### ISSUE TITLE
Looking for firmware for "rs40rgb" keyboard

### ISSUE THREAD

**Issue by abstrakct** [Oh-My-Mechanical-Keyboard/qmk_firmware#11]
Hello, apologies if this is the wrong place to ask. But I am trying to find working firmware for a keyboard called "rs40rgb" which I bought on aliexpress. The keyboard worked fine when I got it, but I tried to flash a custom QMK firmware to it and now my computer does not recognize the usb device. 

This is the keyboard: https://www.aliexpress.com/item/1005004149815917.html?spm=a2g0o.order_list.0.0.31b718026v44Lb

```
Manufacturer: WJC
Product: rs40rgb
VID: AA96
PID: AAAC
```

I think it is similar to this https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/tree/y_and_r_kb_pool/keyboards/yandrstudio/ble/rs40ble
but without the bluetooth.

Can anyone here help me get some working firmware for my keyboard? I am able to put the keyboard in bootloader mode, but all firmwares I have tried do not work.

**Comment by abstrakct** [comment]
nevermind, problem solved

**Comment by andypiper** [comment]
Hi @abstrakct can you share the solution here?
