### ISSUE TITLE
can you submit a pull request to qmk/qmk_firmware for this repo?

### ISSUE THREAD

**Issue by razamatan** [Oh-My-Mechanical-Keyboard/qmk_firmware#25]
### Describe the Bug

i have the hotdoxv2 keyboard, and it would be great to upstream this into the root qmk firmware.

otherwise, do you mind if i submit the hotdoxv2 upstream myself?

### Link to product page (if applicable)

https://kono.store/products/ergodox-76-hot-dox-mechanical-keyboard-v2

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by jiaxin96** [comment]
Soon this will be, we will submit it to the QMK upstream after code review again.
