### ISSUE TITLE
[Bug] hotdox76v2 RGB_MATRIX configuration isn't correct

### ISSUE THREAD

**Issue by LensPlaysGames** [Oh-My-Mechanical-Keyboard/qmk_firmware#26]
### Describe the Bug

The ergodox hotdox76v2 RGB_MATRIX configuration is incorrect when it comes to the right side RGB addressing. For example, the `REACTIVE_SIMPLE` mode works correctly on the left side, but the wrong key lights up on the right side i.e. when `H` is pressed, the key to the right of `;` lights up. This is not ideal behaviour, clearly. Also, the `DIGITAL_RAIN` mode is upside-down on both halves, with the right half not even lighting up in columns, kind of just randomly. I suspect this is due to the RGB Matrix configuration.

### Keyboard Used

yandrstudio/wired/hotdox76v2

### Operating System

Windows 10

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.1
Ψ QMK home: D:/Programming/ergodox/ergodox76_hotdoxv2_qmk_firmware
Ψ Detected Windows 10 (10.0.19044).
Ψ Git branch: lens_r
Ψ Repo version: 0.13.38
⚠ Git has unstashed/uncommitted changes.
⚠ The official repository does not seem to be configured as git remote "upstream".
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.1.0
Ψ Found avr-gcc version 8.5.0
Ψ Found avrdude version 7.0
Ψ Found dfu-util version 0.11
Ψ Found dfu-programmer version 0.7.2
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2022-06-11 09:09:45 +0000 --  (f836d24b0)
Ψ - lib/chibios-contrib: 2022-07-27 10:46:15 +0200 --  (d03aa9cc)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/pico-sdk: 2022-05-17 19:19:01 +0200 --  (07edde8)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ QMK is ready to go, but minor problems were found
```

### Is AutoHotKey / Karabiner installed

- [X] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

### Additional Context

The git fork I'm on is available on my GH profile. I didn't alter any of the RGB_MATRIX configuration, just added my own keymap with `qmk new-keymap` and then changed some `rules.mk` to save firmware space, and enable RGB_MATRIX instead of RGB_LIGHT, which is the default.

**Comment by jiaxin96** [comment]
You may need to update the QMK version. I have no problem compiling locally.
here is my qmk doctor output info
```shell
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.0.0
Ψ QMK home: /home/jx/PRJ/KBs/qmk_firmware
Ψ Detected Linux (WSL).
Ψ Git branch: y_and_r_kb_pool
Ψ Repo version: 0.18.15
Ψ - Latest y_and_r_kb_pool: 2022-11-18 15:13:53 +0800 (5e90930270) -- Merge pull request #28 from LoliPain/ws69userprocessing
Ψ - Latest upstream/master: 2022-11-05 10:55:42 -0700 (e3a97eb1c8) -- [Keyboard] Add Work Louder Numpad (#18912)
Ψ - Latest upstream/develop: 2022-11-07 16:16:41 +1100 (4deaa58016) -- `cannonkeys/db60/hotswap`: fix layouts (#18982)
Ψ - Common ancestor with upstream/master: 2022-10-28 18:48:08 +0800 (6514c25ca6) -- Docs: fix a typo (#18896)
Ψ - Common ancestor with upstream/develop: 2022-10-28 18:48:08 +0800 (6514c25ca6) -- Docs: fix a typo (#18896)
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 9.2.1
Ψ Found avr-gcc version 5.4.0
Ψ Found avrdude version 6.3-20171130
Ψ Found dfu-util version 0.9
Ψ Found dfu-programmer version 0.6.1
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2022-06-11 09:09:45 +0000 --  (f836d24b0)
Ψ - lib/chibios-contrib: 2022-07-27 10:46:15 +0200 --  (d03aa9cc)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/pico-sdk: 2022-05-17 19:19:01 +0200 --  (07edde8)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ QMK is ready to go
```

**Comment by LensPlaysGames** [comment]
Wow, thanks for closing when you don't even know what the bug is, lol. There was no problem during compilation, only in the resulting RGB MATRIX effects displaying completely incorrectly on the right hand of the split keyboard.

Also, as for your suggested fix; how would one go about "updating the QMK version"??? All I did was clone the repo and build it.

**Comment by jiaxin96** [comment]
> Wow, thanks for closing when you don't even know what the bug is, lol. There was no problem during compilation, only in the resulting RGB MATRIX effects displaying completely incorrectly on the right hand of the split keyboard.
> 
> Also, as for your suggested fix; how would one go about "updating the QMK version"??? All I did was clone the repo and build it.

I'm sorry I didn't see your problem,. Because you posted the information of QMK doctor, I mistakenly thought it was some compilation problem. And for the lighting problem, because the PCB hardware is not maintained and produced by me, it may take some time to contact the original author to determine the lighting position on the hardware before it can be fixed.

**Comment by LensPlaysGames** [comment]
I see; my mistake then. I was just filling in the entries that are in the issue template.

That's unfortunate; hopefully this can be sorted out, as it would be *so* cool to have the proper key light up when I tap it!!! If you know the specifics of the information needed, maybe I can relay that to the people over at Alpaca keyboards who made this keeb and see if they can get back with it.

**Comment by jiaxin96** [comment]
Maybe later, I can try to update the position matrix of rgb. I have found that this matrix does not correspond to the RGB LED order of the first array of g_led_config.
https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/blob/1a027e8de02986a9c66d4fc959ca4846fe7ea691/keyboards/yandrstudio/wired/hotdox76v2/hotdox76v2.c#L41.
But whether this fix can solve your problem or not still needs to be tested by the PCB owner (maybe yourself).

**Comment by LensPlaysGames** [comment]
I'd be happy to be a bit of a guinea pig and to test out new matrix configs. Anything to see that sweet, sweet RGB glow each time I press a key :p

**Comment by jiaxin96** [comment]
it may take a little time. Now I can only find these 3 pictures left when communicating with PCB designers for reference.
![image](https://user-images.githubusercontent.com/20027416/202690035-d9a5e9ed-d389-491f-af29-d3869730b7bc.png)
![image](https://user-images.githubusercontent.com/20027416/202690064-1945bd52-b8ad-4f6c-8d6f-562c0a175e22.png)
![image](https://user-images.githubusercontent.com/20027416/202690088-5a5e5d6c-b10a-4ccb-b93a-046b6a9642d5.png)

I don't have the schematic diagram of PCB design, PCB production documents or even  a PCB.

**Comment by jiaxin96** [comment]
I'm sorry, I checked the code carefully. If the picture and RGB connection order provided by PCB designer are correct, the current code has no problem according to my understanding. I think you need to provide more infos to help me fix this bug (if it was). For example, when the right part key is pressed, which key lights up.

**Comment by LensPlaysGames** [comment]
Thank you! It's okay.

I will reflash the RGB matrix firmware when I can (hopefully today) and write down or make a picture of what key lights up when I press each key. I did mention in the original that when H is pressed, the double quote key lights up (five keys to the right)

To me, it looks like there are no underglow LEDs in those pictures; there are 5 LEDs that face downwards and aren't for any one key. The right side appears to be offset by five keys, so if these aren't accounted for that would make sense to me

**Comment by LensPlaysGames** [comment]
I've traced the backlight PCB traces just by eye, and drew a little picture to hopefully help out, if it's needed.

The backlight/underglow LEDs appear to be wired first. The underglow LEDs are represented by a circle, while the squares represent upward facing key LEDs. The pencil represents the trace I was able to follow between them.

![PXL_20221128_112747645.jpg](https://user-images.githubusercontent.com/69637718/204267138-6ca4e7a8-289f-4e18-8647-81a9216f699f.jpg)

KEEP IN MIND this is the RIGHT HAND. It is drawn from the back, which is why the thumb cluster is on the right. So if looking from the top of the keyboard, it would be reversed

**Comment by LensPlaysGames** [comment]
Here is the back side of the right hand PCB.

Let me know if any pics of certain areas or components in more detail are wanted or needed.

![PXL_20221128_114337551.NIGHT.jpg](https://user-images.githubusercontent.com/69637718/204269792-c81a17fb-fcf3-48b6-9291-1c8059affca9.jpg)

**Comment by LensPlaysGames** [comment]
Also, I did want to mention that the RGB_MATRIX effects that are *not* reactive, like the left to right vertical band, actually work just fine. It is only the reactive animations that are incorrect.

**Comment by LensPlaysGames** [comment]
And _finally_, we have a video demonstrating the issue.

https://youtu.be/zigxA9TN5r0

Again, if there is anything more I can provide, please let me know.

**Comment by LensPlaysGames** [comment]
Two things:

1. Should I switch to the official QMK repo, now that it has `hotdox76v2` as a builtin community keyboard?
2. Is this line supposed to be RGB_MATRIX_NUM or something? It's odd to see RGBLED mentioned in the RGB matrix config... 

https://github.com/LensPlaysGames/ergodox76_hotdoxv2_qmk_firmware/blob/be7bf4da8f7159a19952f47ff34dd26a9c291662/keyboards/yandrstudio/wired/hotdox76v2/config.h#L68

**Comment by LensPlaysGames** [comment]
I fixed it! Well, I put a bandaid on, and it *sort of* works now.

```diff
diff --git a/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h b/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h
index f9584d7071..3334bc58ee 100644
--- a/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h
+++ b/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h
@@ -21,7 +21,14 @@ bool effect_runner_reactive(effect_params_t* params, reactive_f effect_func) {
 
         uint16_t offset = scale16by8(tick, qadd8(rgb_matrix_config.speed, 1));
         RGB      rgb    = rgb_matrix_hsv_to_rgb(effect_func(rgb_matrix_config.hsv, offset));
-        rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
+        // TODO/FIXME: This is the stupidest fix ever for the
+        // hotdox76v2 right hand side LED matrix being offset for
+        // reactive lighting.
+        if (is_keyboard_left()) {
+          rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
+        } else {
+          rgb_matrix_set_color(i + 5, rgb.r, rgb.g, rgb.b);
+        }
     }
     return rgb_matrix_check_finished_leds(led_max);
 }
```

This **works**. It obviously is not ideal, and should not be the way to do things, but I hope that this fixing the issue will point you to where it actually lies.

When I say it "works", I mean that when I press the "O" key, the LED corresponding to that key lights up. However, it doesn't work *perfectly*. The five top right most of the right hand side keys light up the underglow on the left still, and sometimes get "stuck" in their displayed color. This leads me further to believe that RGB_MATRIX configuration is not taking the underglow LEDs into account.

**Comment by LensPlaysGames** [comment]
Could it be that the hardware is layed out as a `/38/38/5/5` and the software is layed out `/38/5/38/5`? This seems like it would cause the exact bug that occurs, given the contents of `setled()` and friends

**Comment by jiaxin96** [comment]
> Also, I did want to mention that the RGB_MATRIX effects that are _not_ reactive, like the left to right vertical band, actually work just fine. It is only the reactive animations that are incorrect.

This is very helpful. I will adjust it according to this. Thank you for your feedback.

**Comment by jiaxin96** [comment]
> And _finally_, we have a video demonstrating the issue.
> 
> https://youtu.be/zigxA9TN5r0
> 
> Again, if there is anything more I can provide, please let me know.

This is very helpful. I will adjust it according to this. Thank you for your feedback.

**Comment by jiaxin96** [comment]
> I fixed it! Well, I put a bandaid on, and it _sort of_ works now.
> 
> ```diff
> diff --git a/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h b/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h
> index f9584d7071..3334bc58ee 100644
> --- a/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h
> +++ b/quantum/rgb_matrix/animations/runners/effect_runner_reactive.h
> @@ -21,7 +21,14 @@ bool effect_runner_reactive(effect_params_t* params, reactive_f effect_func) {
>  
>          uint16_t offset = scale16by8(tick, qadd8(rgb_matrix_config.speed, 1));
>          RGB      rgb    = rgb_matrix_hsv_to_rgb(effect_func(rgb_matrix_config.hsv, offset));
> -        rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
> +        // TODO/FIXME: This is the stupidest fix ever for the
> +        // hotdox76v2 right hand side LED matrix being offset for
> +        // reactive lighting.
> +        if (is_keyboard_left()) {
> +          rgb_matrix_set_color(i, rgb.r, rgb.g, rgb.b);
> +        } else {
> +          rgb_matrix_set_color(i + 5, rgb.r, rgb.g, rgb.b);
> +        }
>      }
>      return rgb_matrix_check_finished_leds(led_max);
>  }
> ```
> 
> This **works**. It obviously is not ideal, and should not be the way to do things, but I hope that this fixing the issue will point you to where it actually lies.
> 
> When I say it "works", I mean that when I press the "O" key, the LED corresponding to that key lights up. However, it doesn't work _perfectly_. The five top right most of the right hand side keys light up the underglow on the left still, and sometimes get "stuck" in their displayed color. This leads me further to believe that RGB_MATRIX configuration is not taking the underglow LEDs into account.

It does seem that the problem is the rgb_matrix offset caused by the underglow led. Can you see whether the underglow led or the key-led is connected first from the chip on the right side?

**Comment by jiaxin96** [comment]
> Here is the back side of the right hand PCB.
> 
> Let me know if any pics of certain areas or components in more detail are wanted or needed.
> 
> ![PXL_20221128_114337551.NIGHT.jpg](https://user-images.githubusercontent.com/69637718/204269792-c81a17fb-fcf3-48b6-9291-1c8059affca9.jpg)

I'm sure the keyboard is a modified version for this repo. The picture that the author showed me when I first made the firmware was a 32u4-AU chip.

**Comment by jiaxin96** [comment]
According to the information you provided, I added 5 underglow offsets to the rgb_matrix on the right side. The right-keyboard should work normally now, but it still needs hard work for you to test.

here is my fix:

https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/commit/2228c19453fabd7d7a5bee058d9c22fa84dabbb0

**Comment by LensPlaysGames** [comment]
Thank you so much!! I will try it as soon as possible :pray:

**Comment by LensPlaysGames** [comment]
> Can you see whether the underglow led or the key-led is connected first from the chip on the right side?

I will clean off my glasses and do my best to see the traces; I'll get a good picture if I can

**Comment by jiaxin96** [comment]
> 

Haha, maybe you can use the buzzer of multimeter to find the connection.

**Comment by jiaxin96** [comment]
> Thank you so much!! I will try it as soon as possible 🙏

Has the bug been solved now? If it has been fixed, I will submit this keyboard to the main branch of qmk.
