### ISSUE TITLE
About the code on Moonlight RE75 V2

### ISSUE THREAD

**Issue by HorrorTroll** [Oh-My-Mechanical-Keyboard/qmk_firmware#29]
Hi @jiaxin96, I'm sorry if I disturbing you. I just want to ask about the code on Moonlight RE75 V2,

So, I was buying this keyboard and wonder is there anyway I could do thing like custom OLED screen with Bongo Cat on it? Because I can't compile the code from ml75r2ble.

**Comment by jiaxin96** [comment]
it needs some modifications on the oled driver code. Code snippets can refer to the following link: https://gist.github.com/jiaxin96/72d575b1b73799acf297504f04a90025
