### ISSUE TITLE
[Bug] `Toggle macOS Keymap` 并非切换为标准mac键盘布局

### ISSUE THREAD

**Issue by jimlee2048** [Oh-My-Mechanical-Keyboard/qmk_firmware#36]
### Describe the Bug

`customKeycodes` 中用于切换mac键盘布局的自定义键值`Toggle macOS Keymap`的触发行为不太正确，并非切换为标准mac布局
https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/blob/231a617723b41b6d49e3c2db4fd091ccfaf6cbe8/keyboards/yandrstudio/ble/nz67ble/info-via-nz67ble-v2x.json#L66-L70
https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/blob/231a617723b41b6d49e3c2db4fd091ccfaf6cbe8/keyboards/yandrstudio/ble/nz67ble/nz67ble.h#L56

## 当前行为
https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/blob/231a617723b41b6d49e3c2db4fd091ccfaf6cbe8/keyboards/yandrstudio/ble/nz67ble/nz67ble.c#L162-L166

触发[Magic Keycodes](https://docs.qmk.fm/#/keycodes?id=magic-keycodes)中的 `CG_TOGG`，交换 Ctrl 和 GUI，如图所示：

![image](https://user-images.githubusercontent.com/21117946/211002451-d9f69a0f-b292-4637-8fb8-4bbd23a3c82e.png)

然而，这样切换后的布局并非标准Mac键盘布局：（以完整配列的Apple妙控键盘为例，如下图所示）

![image](https://user-images.githubusercontent.com/21117946/211002715-eab36b27-bfe3-4ba6-ae6f-7da65e02ae77.png)

## 期望行为
参考上图标准mac键盘布局，期望触发[Magic Keycodes](https://docs.qmk.fm/#/keycodes?id=magic-keycodes) 中的`AG_TOGG`，切换时交换原布局上 GUI 和 Alt。如下图所示：

![image](https://user-images.githubusercontent.com/21117946/211003540-dcd535dc-c6d2-4880-87dc-62feaa3827ea.png)

以下是其他键盘套件/量产键盘兼容mac布局行为的一些参考：

键盘套件 贱驴rs2 的mac布局切换行为：
![键盘套件 贱驴rs2 的mac布局切换行为](https://user-images.githubusercontent.com/21117946/210977792-dfbb3434-c5b0-4093-9aaa-a79603a3b8d0.png)

量产键盘 罗技MX Keys 的双布局标识：
![量产键盘 罗技MX Keys 的双布局标识](https://user-images.githubusercontent.com/21117946/210978235-0a8a0145-8376-4687-bb30-c5c15bd898a1.png)
 

### Keyboard Used

yandrstudio/ble/nz67ble

### Link to product page (if applicable)

https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/tree/y_and_r_kb_pool/keyboards/yandrstudio/ble/nz67ble

### Operating System

macOS

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by jiaxin96** [comment]
感谢您的修正，如果按照标准macos的方式的话确实需要触发AG_TOGG。键盘采用CG_TOGG更多的是为了迎合一些拥有win键盘的玩家使用习惯，因为在macos上command的很多作用都很像ctrl在win上的作用，所以yr的键盘在生产的时候默认采用了CG_TOGG来作为macos布局触发按键，不过以标准macos布局来讲这个确实是一个错误的定义，我们会在后面的生产中采用另一个名称定义CG_TOGG，并修改TogMacLayout按键为触发AG_TOGG。不过还是期望VIA能够引入这些按键的定义，这样才是最好的解决方案。最后，再次感谢您的指正。

**Comment by jiaxin96** [comment]
For the update firmeware and via3 config json, you can find in this release: https://github.com/Oh-My-Mechanical-Keyboard/oh-my-mechanical-keyboard.github.io/releases/tag/nz67ble_update.
