### ISSUE TITLE
[Bug] Cannot get into bootloader mode - tg67

### ISSUE THREAD

**Issue by eldenpark** [Oh-My-Mechanical-Keyboard/qmk_firmware#38]
### Describe the Bug

Hi, I'm trying to install my custom qmk key configuration onto the board.

I've tried with both in Mac M1 and Linux environment using both qmk and qmk-toolbox (GUI) but it seems like I cannot get into bootloader mode. `qmk doctor` says I'm good to go.

When I plug in the keyboard while ESC key pressed, I can get the "bootloader" partition connected onto my filesystem in which I can find .uf2 file. I assume that it is the bootloader mode. But the `Flash` button in the qmk toolbox is still disabled and in the console nothing happens (like there's no yellow logs or whatever which I think should appear at some point)

Can anyone help here? Is it the problem on the PCB, or am I missing something?

### Keyboard Used

yandrstudio/tg67

### Operating System

Ubuntu 22, OSX 13

### qmk doctor Output

```text
Ψ QMK Doctor is checking your environment.
Ψ CLI version: 1.1.1
Ψ QMK home: /home/ubuntu/qmk_firmware
Ψ Detected Linux (Ubuntu 22.04.2 LTS).
Ψ Git branch: tg67/1
Ψ Repo version: 0.20.1
Ψ - Latest tg67/1: 2023-03-10 00:53:10 +0900 (a5393c16c5) -- o
Ψ - Latest upstream/master: 2023-03-10 05:23:53 -0500 (bf4121a770) -- [Keyboard] Add Ortho48v2 Keyboard (#18889)
Ψ - Latest upstream/develop: None
Ψ - Common ancestor with upstream/master: 2023-03-08 12:58:23 -0700 (9c79d2933c) -- [Doc] Update PR checklist (#19988)
Ψ - Common ancestor with upstream/develop: None
Ψ All dependencies are installed.
Ψ Found arm-none-eabi-gcc version 10.3.1
Ψ Found avr-gcc version 5.4.0
Ψ Found avrdude version 6.3-20171130
Ψ Found dfu-programmer version 0.6.1
Ψ Found dfu-util version 0.9
Ψ Submodules are up to date.
Ψ Submodule status:
Ψ - lib/chibios: 2023-01-03 19:29:26 +0000 --  (0062927e3)
Ψ - lib/chibios-contrib: 2023-01-11 16:42:27 +0100 --  (a224be15)
Ψ - lib/googletest: 2021-06-11 06:37:43 -0700 --  (e2239ee6)
Ψ - lib/lufa: 2022-08-26 12:09:55 +1000 --  (549b97320)
Ψ - lib/vusb: 2022-06-13 09:18:17 +1000 --  (819dbc1)
Ψ - lib/printf: 2022-06-29 23:59:58 +0300 --  (c2e3b4e)
Ψ - lib/pico-sdk: 2023-02-12 20:19:37 +0100 --  (a3398d8)
Ψ - lib/lvgl: 2022-04-11 04:44:53 -0600 --  (e19410f8)
Ψ QMK is ready to go
```

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by jiaxin96** [comment]
The released tg67 firmware uses the modified uf2 boot loader by default. You can refer to this issue (https://github.com/qmk/qmk_firmware/pull/18278) for more information. If you want to use qmk to identify the bootloader of stm32f103, you need to use stm32duino.

**Comment by jiaxin96** [comment]
For the bootloader types supported by qmk, you can refer to qmk_toolbos https://github.com/qmk/qmk_toolbox. And for more information about the us2 bootloader in qmk, you need to refer to the qmk doc (https://docs.qmk.fm/#/flashing?id=tinyuf2). And if you want to build your tg67 firmware, it is It is a good chose to compile using the y_and_r_kb_pool brance of this repository instated of the upstream of  qmk master branch (https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/tree/y_and_r_kb_pool).

Here is the tg67 files https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/tree/y_and_r_kb_pool/keyboards/yandrstudio/wired/tg67
