### ISSUE TITLE
[Bug] Column 13 not working after flash

### ISSUE THREAD

**Issue by tomater33** [Oh-My-Mechanical-Keyboard/qmk_firmware#39]
### Describe the Bug

Hi, I'm trying to flash multiple Nz64 RGB REV 1.0 boards manufactured by Y&R with my custom QMK configuration.

I've tried both compiling and flashing these boards with and without VIA support and using all 3 operating systems and this issue seems to be happening in every scenario.

I can get into bootloader mode just fine by shorting _bt0_ and _vcc_ and successfully flash my custom firmware, or for instance the one on this github without any changes, and the keyboard boots just fine, but right when I start testing my layout I can notice column 13 appears pressed down on VIA configurator and just doesn't work at all, this issue is persistent even without VIA support enabled.

![image](https://user-images.githubusercontent.com/128935826/227743994-3e949023-8ba6-4958-8b0b-3d73edab2464.png)

This board should use the A9 pin, since I've tested it with a multimeter and the circuit going from A9 goes to to the bottom row of column 13.

Based on the testing I've done this shouldn't be an issue on the PCB itself, since I highly doubt i somehow managed to short 6 boards and all of them work fine when using a multimeter to check if the circuit coming from the A9 pin is broken.

In case this is important, this board is using a **STM32F401CCU6** and came in an epomaker cat mini 64, but other spare boards with the same revision number are having that issue regardless of where I get them.

### Keyboard Used

yandrstudio/nz64

### Operating System

macOS 13, Fedora 37, Windows 10

### Is AutoHotKey / Karabiner installed

- [ ] AutoHotKey (Windows)
- [ ] Karabiner (macOS)

**Comment by jiaxin96** [comment]
For keyboards using the f401, if using the default scanning algorithm, there may be problems when using the a9 pin. The solution is to use the modified scanning algorithm (in this repo, you can referance the file https://github.com/Oh-My-Mechanical-Keyboard/qmk_firmware/blob/y_and_r_kb_pool/keyboards/yandrstudio/wired/nz64/f401/matrix.c) or change the error definition in the upstream Chibios (lib\chibios\os\hal\ports\STM32\LLD\OTGv1\hal_usb_lld.c line:43). For more information about this bug, please refer to this issue https://github.com/qmk/qmk_firmware/issues/7855
