### ISSUE TITLE
编译不了缺少文件

### ISSUE THREAD

**Issue by kiritro** [Oh-My-Mechanical-Keyboard/qmk_firmware#6]
r: biu_ble_common.h: No such file or directory
   19 | #include "biu_ble_common.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
 [ERRORS]

缺少biu_ble_common.h

**Comment by shuihuohuooo** [comment]
> 
因为biu总并没有开源完整

**Comment by jiaxin96** [comment]
后面会以二进制的动态库形式开放

**Comment by 0x5ea000000** [comment]
Sorry for bothering you, is biu library binary available now? @jiaxin96
